/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author javi
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumObrerasExterior = new javax.swing.JLabel();
        jLabelNumObrerasInterior = new javax.swing.JLabel();
        jLabelNumSoldadoInstruccion = new javax.swing.JLabel();
        jLabelNumSoldadoLuchando = new javax.swing.JLabel();
        jLabelNumCriasComiendo = new javax.swing.JLabel();
        jLabelNumCriasRefugio = new javax.swing.JLabel();
        jTextFieldNumObrerasExterior = new javax.swing.JTextField();
        jTextFieldNumObrerasInterior = new javax.swing.JTextField();
        jTextFieldNumSoldadoInstruccion = new javax.swing.JTextField();
        jTextFieldNumSoldadoLuchando = new javax.swing.JTextField();
        jTextFieldNumCriasComiendo = new javax.swing.JTextField();
        jTextFieldNumCriasRefugio = new javax.swing.JTextField();
        jButtonGenerarAmenaza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNumObrerasExterior.setText("Número de hormigas obreras en el exterior de la colonia");

        jLabelNumObrerasInterior.setText("Número de hormigas obreras en el interior de la colonia");

        jLabelNumSoldadoInstruccion.setText("Número de hormigas soldado haciendo instrucción");

        jLabelNumSoldadoLuchando.setText("Número de hormigas soldado repeliendo una invasión");

        jLabelNumCriasComiendo.setText("Número de hormigas crías en la ZONA PARA COMER");

        jLabelNumCriasRefugio.setText("Número de hormigas crías en el REFUGIO");

        jButtonGenerarAmenaza.setText("Generar Amenaza Insecto Invasor");
        jButtonGenerarAmenaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarAmenazaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumObrerasExterior)
                    .addComponent(jLabelNumObrerasInterior)
                    .addComponent(jLabelNumSoldadoInstruccion)
                    .addComponent(jLabelNumSoldadoLuchando)
                    .addComponent(jLabelNumCriasComiendo)
                    .addComponent(jLabelNumCriasRefugio))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNumSoldadoInstruccion)
                    .addComponent(jTextFieldNumObrerasExterior)
                    .addComponent(jTextFieldNumObrerasInterior)
                    .addComponent(jTextFieldNumCriasRefugio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumCriasComiendo)
                    .addComponent(jTextFieldNumSoldadoLuchando))
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jButtonGenerarAmenaza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumObrerasExterior)
                    .addComponent(jTextFieldNumObrerasExterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumObrerasInterior)
                    .addComponent(jTextFieldNumObrerasInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumSoldadoInstruccion)
                    .addComponent(jTextFieldNumSoldadoInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumSoldadoLuchando)
                    .addComponent(jTextFieldNumSoldadoLuchando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumCriasComiendo)
                    .addComponent(jTextFieldNumCriasComiendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumCriasRefugio)
                    .addComponent(jTextFieldNumCriasRefugio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jButtonGenerarAmenaza)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarAmenazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarAmenazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGenerarAmenazaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarAmenaza;
    private javax.swing.JLabel jLabelNumCriasComiendo;
    private javax.swing.JLabel jLabelNumCriasRefugio;
    private javax.swing.JLabel jLabelNumObrerasExterior;
    private javax.swing.JLabel jLabelNumObrerasInterior;
    private javax.swing.JLabel jLabelNumSoldadoInstruccion;
    private javax.swing.JLabel jLabelNumSoldadoLuchando;
    private javax.swing.JTextField jTextFieldNumCriasComiendo;
    private javax.swing.JTextField jTextFieldNumCriasRefugio;
    private javax.swing.JTextField jTextFieldNumObrerasExterior;
    private javax.swing.JTextField jTextFieldNumObrerasInterior;
    private javax.swing.JTextField jTextFieldNumSoldadoInstruccion;
    private javax.swing.JTextField jTextFieldNumSoldadoLuchando;
    // End of variables declaration//GEN-END:variables
}
