/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author javi
 */
public class Servidor extends javax.swing.JFrame {

    /**
     * Creates new form Servidor
     */
    public Servidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelExteriorColonia = new javax.swing.JLabel();
        jLabelInteriorColonia = new javax.swing.JLabel();
        jButtonDetener = new javax.swing.JButton();
        jButtonReanudar = new javax.swing.JButton();
        jButtonGenerarAmenaza = new javax.swing.JButton();
        jLabelHormigasBuscandoComida = new javax.swing.JLabel();
        jLabelHormigasRepeliendoInsecto = new javax.swing.JLabel();
        jTextFieldHormigasBuscandoComida = new javax.swing.JTextField();
        jTextFieldHormigasRepeliendoInsecto = new javax.swing.JTextField();
        jLabelHormigasAlmacen = new javax.swing.JLabel();
        jTextFieldHormigasAlmacen = new javax.swing.JTextField();
        jLabelHormigasLlevandoComida = new javax.swing.JLabel();
        jTextFieldHormigasLlevandoComida = new javax.swing.JTextField();
        jLabelHormigasHaciendoInstruccion = new javax.swing.JLabel();
        jTextFieldHormigasHaciendoInstruccion = new javax.swing.JTextField();
        jLabelHormigasDescansando = new javax.swing.JLabel();
        jTextFieldHormigasDescansando = new javax.swing.JTextField();
        jLabelComidaAlmacen = new javax.swing.JLabel();
        jLabelComidaZonaComer = new javax.swing.JLabel();
        jLabelZonaComer = new javax.swing.JLabel();
        jTextFieldComidaAlmacen = new javax.swing.JTextField();
        jTextFieldZonaParaComer = new javax.swing.JTextField();
        jTextFieldZonaComer = new javax.swing.JTextField();
        jLabelRefugio = new javax.swing.JLabel();
        jTextFieldRefugio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelExteriorColonia.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabelExteriorColonia.setText("Exterior de la colonia");

        jLabelInteriorColonia.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabelInteriorColonia.setText("Interior de la colonia");

        jButtonDetener.setText("Detener");
        jButtonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetenerActionPerformed(evt);
            }
        });

        jButtonReanudar.setText("Reanudar");

        jButtonGenerarAmenaza.setText("Generar Amenaza Insecto Invasor");

        jLabelHormigasBuscandoComida.setText("Hormigas buscando comida");

        jLabelHormigasRepeliendoInsecto.setText("Hormigas repeliendo un insecto invasor");

        jLabelHormigasAlmacen.setText("Hormigas en el ALMACÉN DE COMIDA");

        jLabelHormigasLlevandoComida.setText("Hormigas llevando comida a la ZONA PARA COMER");

        jTextFieldHormigasLlevandoComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHormigasLlevandoComidaActionPerformed(evt);
            }
        });

        jLabelHormigasHaciendoInstruccion.setText("Hormigas haciendo INSTRUCCIÓN");

        jLabelHormigasDescansando.setText("Hormigas descansando");

        jLabelComidaAlmacen.setText("Unidades de comida en ALMACÉN");

        jLabelComidaZonaComer.setText("Unidades de comida en ZONA PARA COMER");

        jLabelZonaComer.setText("ZONA PARA COMER");

        jLabelRefugio.setText("REFUGIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelExteriorColonia)
                            .addComponent(jLabelInteriorColonia)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelHormigasDescansando)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldHormigasDescansando, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 179, Short.MAX_VALUE)
                                        .addComponent(jLabelComidaAlmacen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldComidaAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabelComidaZonaComer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldZonaParaComer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelHormigasHaciendoInstruccion)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldHormigasHaciendoInstruccion))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelHormigasRepeliendoInsecto)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldHormigasRepeliendoInsecto))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelHormigasBuscandoComida)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldHormigasBuscandoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelHormigasAlmacen)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldHormigasAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelHormigasLlevandoComida)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldHormigasLlevandoComida)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelZonaComer)
                                            .addComponent(jLabelRefugio))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldRefugio)
                                            .addComponent(jTextFieldZonaComer))))))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonDetener)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReanudar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGenerarAmenaza)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExteriorColonia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHormigasBuscandoComida)
                    .addComponent(jTextFieldHormigasBuscandoComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHormigasRepeliendoInsecto)
                    .addComponent(jTextFieldHormigasRepeliendoInsecto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabelInteriorColonia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHormigasAlmacen)
                    .addComponent(jTextFieldHormigasAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHormigasLlevandoComida)
                    .addComponent(jTextFieldHormigasLlevandoComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHormigasHaciendoInstruccion)
                    .addComponent(jTextFieldHormigasHaciendoInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHormigasDescansando)
                    .addComponent(jTextFieldHormigasDescansando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelComidaAlmacen)
                    .addComponent(jTextFieldComidaAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComidaZonaComer)
                    .addComponent(jTextFieldZonaParaComer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldZonaComer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZonaComer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRefugio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRefugio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDetener)
                    .addComponent(jButtonReanudar)
                    .addComponent(jButtonGenerarAmenaza))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetenerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDetenerActionPerformed

    private void jTextFieldHormigasLlevandoComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHormigasLlevandoComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHormigasLlevandoComidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetener;
    private javax.swing.JButton jButtonGenerarAmenaza;
    private javax.swing.JButton jButtonReanudar;
    private javax.swing.JLabel jLabelComidaAlmacen;
    private javax.swing.JLabel jLabelComidaZonaComer;
    private javax.swing.JLabel jLabelExteriorColonia;
    private javax.swing.JLabel jLabelHormigasAlmacen;
    private javax.swing.JLabel jLabelHormigasBuscandoComida;
    private javax.swing.JLabel jLabelHormigasDescansando;
    private javax.swing.JLabel jLabelHormigasHaciendoInstruccion;
    private javax.swing.JLabel jLabelHormigasLlevandoComida;
    private javax.swing.JLabel jLabelHormigasRepeliendoInsecto;
    private javax.swing.JLabel jLabelInteriorColonia;
    private javax.swing.JLabel jLabelRefugio;
    private javax.swing.JLabel jLabelZonaComer;
    private javax.swing.JTextField jTextFieldComidaAlmacen;
    private javax.swing.JTextField jTextFieldHormigasAlmacen;
    private javax.swing.JTextField jTextFieldHormigasBuscandoComida;
    private javax.swing.JTextField jTextFieldHormigasDescansando;
    private javax.swing.JTextField jTextFieldHormigasHaciendoInstruccion;
    private javax.swing.JTextField jTextFieldHormigasLlevandoComida;
    private javax.swing.JTextField jTextFieldHormigasRepeliendoInsecto;
    private javax.swing.JTextField jTextFieldRefugio;
    private javax.swing.JTextField jTextFieldZonaComer;
    private javax.swing.JTextField jTextFieldZonaParaComer;
    // End of variables declaration//GEN-END:variables
}
